### ISSUE TITLE
When I import this it occurs an error.

### ISSUE THREAD

**Issue by PradeepSimba** [JPro-one/HelloJPro#8]
When I import this it occurs an error like this .
![jpro](https://user-images.githubusercontent.com/45443554/81535840-2394a180-9388-11ea-902c-416131141e37.PNG)

Then , I changed this project to java sdk 14.
after, I run this project it comes like this.
![jpro2](https://user-images.githubusercontent.com/45443554/81536258-e1b82b00-9388-11ea-89b8-dd84ed12ac50.PNG)

`13:07:48: Executing task 'jproRun'...

Starting Gradle Daemon...
Gradle Daemon started in 37 s 6 ms
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
	at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109)
	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
	at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:209)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:107)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:85)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
	at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
	at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
	at groovy.lang.Binding.<init>(Binding.java:35)
	at groovy.lang.Script.<init>(Script.java:39)
	at org.gradle.groovy.scripts.Script.<init>(Script.java:25)
	at org.gradle.groovy.scripts.BasicScript.<init>(BasicScript.java:34)
	at org.gradle.groovy.scripts.DefaultScript.<init>(DefaultScript.java:69)
	at org.gradle.initialization.InitScript.<init>(InitScript.java:22)
	at ijresolvers_d4f70zswskycngkhint5a409q.<init>(C:\Users\prade\AppData\Local\Temp\ijresolvers.gradle)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:62)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.getScript(DefaultScriptRunnerFactory.java:56)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:86)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:227)
	at org.gradle.configuration.DefaultScriptTarget.addConfiguration(DefaultScriptTarget.java:74)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:232)
	at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:66)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:63)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:49)
	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:63)
	at org.gradle.configuration.DefaultInitScriptProcessor.process(DefaultInitScriptProcessor.java:50)
	at org.gradle.initialization.InitScriptHandler$1.run(InitScriptHandler.java:55)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.initialization.InitScriptHandler.executeScripts(InitScriptHandler.java:49)
	at org.gradle.initialization.DefaultSettingsPreparer.prepareSettings(DefaultSettingsPreparer.java:33)
	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.doLoadBuild(BuildOperatingFiringSettingsPreparer.java:59)
	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.run(BuildOperatingFiringSettingsPreparer.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.initialization.BuildOperatingFiringSettingsPreparer.prepareSettings(BuildOperatingFiringSettingsPreparer.java:42)
	at org.gradle.initialization.DefaultGradleLauncher.prepareSettings(DefaultGradleLauncher.java:190)
	at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:134)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:126)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:106)
	at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:60)
	at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:57)
	at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:85)
	at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:78)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:189)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:78)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:57)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:54)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:51)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:78)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:68)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:27)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)

FAILURE: Build failed with an exception.

* What went wrong:
Could not create an instance of type ijresolvers_d4f70zswskycngkhint5a409q.
> Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s
13:08:41: Task execution finished 'jproRun'.`

How can I solve this ?

**Comment by FlorianKirmaier** [comment]
Thank you for the bug report.
The provided gradle-version didn't support Java14. I've updated it, and it works now with with every version starting with 11.

**Comment by PradeepSimba** [comment]
My project structure

![My project strecture](https://user-images.githubusercontent.com/45443554/81561132-50f54580-93b0-11ea-85e6-2201436cedc6.PNG)

When I run this it occurs an error like this.

![server error](https://user-images.githubusercontent.com/45443554/81561201-71bd9b00-93b0-11ea-9d86-bd27ddf2800c.PNG)

`17:45:57: Executing task 'jproRun'...

Starting Gradle Daemon...
Gradle Daemon started in 14 s 537 ms

> Configure project :
Found module name 'org.openjfx.gradle.javafx.test'

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :prepareBrowser
This application is already running (Or delete D:\Github\HelloJPro\RUNNING_PID file).

> Task :jproRun

Server could not be started. Error-Code: -1

> Task :jproRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jproRun'.
> error occurred

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4/userguide/command_line_interface.html#sec:command_line_warnings
4 actionable tasks: 2 executed, 2 up-to-date
17:46:51: Task execution finished 'jproRun'.`


Why this error occurs ?
How can I solve this?

**Comment by FlorianKirmaier** [comment]
Hm, the RUNNING.PID is existing, which usually gets deleting when executing jproRun.
Maybe it was somehow executed twice? That could explain the rare case, where the process doesn't start properly. I would also recommend starting it from the terminal, to avoid IntelliJ specific bugs.

**Comment by FlorianKirmaier** [comment]
I was testing it to start from IntelliJ as a gradle command.
I had to change the JDK from 11Intellij to 11AdoptOpenJDK (Intellij provides an own JDK, which is causing Problem)
Then it worked proberly.

**Comment by PradeepSimba** [comment]
It done. I have a doubt that was can I use awt in jpro?

**Comment by FlorianKirmaier** [comment]
JPro only renderes the JavaFX Scenegraph, so it doesn't really support awt.
You can convert a BufferedImage to a javafx Image in display it in JavaFX.

**Comment by PradeepSimba** [comment]
When I release jpro it comes like this.
![jpro release](https://user-images.githubusercontent.com/45443554/81585387-ba398080-93d1-11ea-8710-e10ea1885b69.PNG)

`21:43:58: Executing task 'jproRelease'...


> Configure project :
Found module name 'org.openjfx.gradle.javafx.test'

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :prepareBrowser
> Task :jproRelease
> Task :jproRelease FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 2 executed, 3 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jproRelease'.
> Could not resolve all files for configuration ':jprojavafxlinux'.
   > Could not download javafx-graphics-11.0.3.4-jpro+0-linux.jar (org.openjfx:javafx-graphics:11.0.3.4-jpro+0)
      > Could not get resource 'https://sandec.bintray.com/repo/org/openjfx/javafx-graphics/11.0.3.4-jpro+0/javafx-graphics-11.0.3.4-jpro+0-linux.jar'.
         > Could not GET 'https://sandec.bintray.com/repo/org/openjfx/javafx-graphics/11.0.3.4-jpro+0/javafx-graphics-11.0.3.4-jpro+0-linux.jar'.
            > No such host is known (sandec.bintray.com)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 18s
21:45:16: Task execution finished 'jproRelease'.`

How can I release Jpro?

**Comment by FlorianKirmaier** [comment]
Try it again. The mentioned artifact exists. Maybe bintray or your internet was unstable - probably bintray.

**Comment by PradeepSimba** [comment]
Yes , It was done .   I saw this Doc  https://www.jpro.one/?page=docs/current/1.4/PC_AS_JPRO_SERVER  . But , I have a doubt.

I am using windows 10 os . How can I make my pc as a server and connect the android phone as a client?

I want to host the jpro as WLAN with the help of  windows 10.

How can I do this?

**Comment by FlorianKirmaier** [comment]
That topic isn't very JPro specific. Use ./gradlew jproRun , make sure your IP is accessible from the outside, open the port in the router. You probably also have to disable the firewall of Windows. And then you can access your application from any device.

**Comment by PradeepSimba** [comment]
How can I run this files in Windows 10?

![24](https://user-images.githubusercontent.com/45443554/81688056-0094eb00-9477-11ea-86c6-db14456bff65.PNG)

**Comment by FlorianKirmaier** [comment]
Currently, we don't support deploying JPro on Windows.
You can either use jproRun from your project directly or alternatively buy support for JPro. Then we will help you to solve the problem by providing Windows support.

**Comment by PradeepSimba** [comment]
How to buy support for Jpro?

**Comment by PradeepSimba** [comment]
After releasing Jpro. How can I run locally in Windows 10 ?

**Comment by PradeepSimba** [comment]
Can I use the Jpro project as a module in another java project?

**Comment by FlorianKirmaier** [comment]
Goto https://www.jpro.one/?page=prices and fill up the buy formular.

No, you cannot run JPro as a library. You can run it with the Maven/Gradle Plugin, or with jproRelease. The Plugins also work on Windows.
After releasing, you can currently only run it on mac and windows.

**Comment by PradeepSimba** [comment]
After releasing, how can I run it on Windows and mac?

**Comment by FlorianKirmaier** [comment]
As mentioned windows is not supported. For mac, you can unzip the generated file and run the start script in the bin folder.

**Comment by PradeepSimba** [comment]
After releasing , There is any alternative way to run JPro on windows os ?

**Comment by FlorianKirmaier** [comment]
As mentioned, you can directly run it from the Gradle/Maven Plugin

**Comment by PradeepSimba** [comment]
How can I make an Jpro app and give to the user with gradle/maven plugin for Windows without releasing?

**Comment by FlorianKirmaier** [comment]
run "./gradlew jproRun" or "mvn jpro:run"

**Comment by PradeepSimba** [comment]
If the user doesn't install the java then how this work?

**Comment by FlorianKirmaier** [comment]
Usually it's running in a Server, which usually is Linux.

**Comment by PradeepSimba** [comment]
How to run the Jpro gradle project without IDE in Windows?

**Comment by PradeepSimba** [comment]
Can I import jpro as a module in another java project and run Jpro?

**Comment by dlemmermann** [comment]
@PradeepSimba looks like you do not know this but the manual can be found here https://www.jpro.one/?page=docs/current/1.1/

**Comment by PradeepSimba** [comment]
I  want to make an app for Windows for the purposes of local run. How can I do this?

**Comment by dlemmermann** [comment]
If you want to run locally you do not need JPRO. Just run the JavaFX client locally.

**Comment by PradeepSimba** [comment]
I want to make a WLAN with JPro in Windows.

**Comment by dlemmermann** [comment]
A "wireless network"????

**Comment by PradeepSimba** [comment]
Yes

**Comment by PradeepSimba** [comment]
So, how can I make a JPro  app for windows and run locally.

**Comment by dlemmermann** [comment]
@FlorianKirmaier I would just close this ticket. I think @PradeepSimba does not completely understand what JPRO is and what it is being used for. I also sense an unwillingness to RTFM.

**Comment by PradeepSimba** [comment]
How can I make a JPro application for windows for local run ?

Is it possible?

**Comment by PradeepSimba** [comment]
I have a doubt that was Can I export JPro app as a jar and run locally?

Is it possible?

**Comment by FlorianKirmaier** [comment]
Why not run it as a JavaFX Application without JPro?

**Comment by PradeepSimba** [comment]
Sir , I want to use the javafx app in my mobile browser with WLAN like this
![a](https://user-images.githubusercontent.com/45443554/82136526-9ab8b280-982c-11ea-894f-b2a4f1dfe172.jpg)

It is just for educational purpose.

**Comment by PradeepSimba** [comment]
How can I export the JPro app as a jar with this configuration ?

![2](https://user-images.githubusercontent.com/45443554/82136723-19fab600-982e-11ea-844e-d64bc94dc277.PNG)
![1](https://user-images.githubusercontent.com/45443554/82136724-1f580080-982e-11ea-8743-4c54df55eed1.PNG)

**Comment by FlorianKirmaier** [comment]
You can't export it as a Jar. You can only JProRelease, which currently only works for Linux and Mac.
You can run it directly with "./gradlew jproRun", in that case you can access the application from a mobile-phone, if your network is configured properly. But I can't help you with that.

**Comment by PradeepSimba** [comment]
Why I can not export the jar and run ? Can you explain in detail?

**Comment by FlorianKirmaier** [comment]
JPro runs in a multiple classloader environment, and it can't be trivially put into a single jar.
The plugins also do a lot like, setting variables depending on configuration, replacing JavaFX with a forked version of JavaFX etc.
What you can do, is bundle your application in a single jar and run it somewhere else with windows by putting it into a minimal gradle project, which only contains the jar as a dependency. But that's usually not very elegant.

**Comment by PradeepSimba** [comment]
How to create JPro project as a jar in intellij ?

Guide me to create JPro project as a  jar file.

**Comment by FlorianKirmaier** [comment]
Look at gradle or maven documentation?

**Comment by PradeepSimba** [comment]
When I run JPro in netbeans  it occurs an error like this.

![1](https://user-images.githubusercontent.com/45443554/82190474-b09ea400-990e-11ea-8be7-9c3970b9b168.PNG)





` JAVA_HOME="C:\Program Files\Java\jdk-13.0.2"
  cd D:\Netbeans\netbeans11\HelloJPro-master; ./gradlew --configure-on-demand -x check jproRun
 Configuration on demand is an incubating feature.

> Configure project :
Found module name 'org.openjfx.gradle.javafx.test'

> Task :compileJava
> Task :processResources UP-TO-DATE
> Task :classes
> Task :prepareBrowser
> Task :jproRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jproRun'.
> java.io.FileNotFoundException: .\logs\application.gradle.log (The system cannot find the path specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 57s
4 actionable tasks: 3 executed, 1 up-to-date
`


How can I solve this?

**Comment by FlorianKirmaier** [comment]
run it from the terminal so you won't encounter buggy Gradle integrations from IDEs.

**Comment by PradeepSimba** [comment]
How to create A JPro project as a jar?
I have trouble with this . I am new to gradle project . I tried to create JPro project as a jar for 4 hours. But , it fail.

Help me to create a JPro project as a jar.

**Comment by FlorianKirmaier** [comment]
https://stackoverflow.com/questions/20700053/how-to-add-local-jar-file-dependency-to-build-gradle-file

**Comment by PradeepSimba** [comment]
How to export a JPro project as a jar?
I have trouble with this . I am new to gradle project . I tried to export JPro project as a jar for 4 hours. But , it fail.

Help me to export a JPro project as a jar with intellij.

**Comment by PradeepSimba** [comment]
But , your answer is to add a local jar in a gradle project. I want to export the JPro as a jar . Help!!!

**Comment by FlorianKirmaier** [comment]
As mentioned, you can't. closing the ticket now.

**Comment by PradeepSimba** [comment]
How to run this jpro app


https://github.com/JPro-one/JPro-from-Jars/issues/1

**Comment by PradeepSimba** [comment]
When I run JPro-from-jars project it comes an error.


https://github.com/JPro-one/JPro-from-Jars/issues/1
